name: GitHub Actions Secret Example

on:
  push:

jobs:

    # The Secrect Actions GitHub example has three steps
    steps:
      # Show how to print unmasked GitHub secrets to the console
      - name: Step 1 - Echo out a GitHub Actions Secret to the logs
        run: |
          echo "The GitHub Action Secret will be masked:  "
          echo ${{ secrets.TOKEN }}
          echo "Trick to echo GitHub Actions Secret:  "
          echo ${{secrets.TOKEN}} | sed 's/./& /g' 

